apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service

spec:
  type: NodePort
  ports: 
   - targetPort: 80
     port: 80
     nodePort: 30000
  selector:
    app: api-gateway
    type: production

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
    type: production

spec:
    containers:
    - name: api-gateway
      image: 
      ports:
      - containerPort: 80
      labels:
        app: api-gateway
        type: production
