apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service

spec:
  type: NodePort
  ports: 
   - targetPort: 80
     port: 80
     nodePort: 30000
  selector:
    app: api-gateway
    type: production

---

apiVersion: v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    type: production
  
  spec:
    containers:
    - name: api-gateway
      image: 
